// <auto-generated />
namespace PD.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Addavatar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addavatar));
        
        string IMigrationMetadata.Id
        {
            get { return "202103292323052_Add avatar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
